{{- if .Values.rbac.create -}}
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: {{ include "replica-count-manager.fullname" . }}-clusterrolebinding
  labels:
    {{- include "replica-count-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "replica-count-manager.fullname" . }}-clusterrole
subjects:
  - kind: ServiceAccount
    name: {{ include "replica-count-manager.serviceAccountName" . }}
    namespace: "{{ .Release.Namespace }}"
{{- end }}
